import { BookOpen, CircleAlert } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import {
  m1V3GradeTone,
  type M1V3PredictionData,
  type M1V3SubjectPrediction,
} from "@/lib/m1v3-prediction"

import { ModelCard } from "./model-card"

function SubjectRow({ item }: { item: M1V3SubjectPrediction }) {
  return (
    <div className="rounded-lg border border-border p-3">
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div className="min-w-0">
          <p className="text-sm font-semibold">{item.subject_id}</p>
          <p className="text-xs text-muted-foreground">Semester {item.semester_no}</p>
        </div>
        <Badge variant={m1V3GradeTone(item.grade_band)}>{item.grade_band}</Badge>
      </div>

      <div className="mt-3 flex flex-wrap items-end gap-6">
        <div>
          <p className="text-[0.6875rem] font-medium tracking-widest text-muted-foreground uppercase">
            Predicted end-sem score
          </p>
          <p className="text-2xl font-semibold tabular-nums">
            {item.predicted_end_sem_marks.toFixed(1)}
            <span className="text-sm font-normal text-muted-foreground">
              {" "}/ {item.target_max}
            </span>
          </p>
        </div>
        {item.grade_label && (
          <div>
            <p className="text-[0.6875rem] font-medium tracking-widest text-muted-foreground uppercase">
              Grade
            </p>
            <p className="text-2xl font-semibold tabular-nums">{item.grade_label}</p>
          </div>
        )}
      </div>

      <div className="mt-3 rounded-md border border-foreground/10 bg-background/40 px-3 py-2.5">
        <p className="text-xs leading-relaxed text-muted-foreground">
          Based on your current academic performance, the model estimates your
          predicted end-semester score in this subject at around{" "}
          {item.predicted_end_sem_marks.toFixed(1)} out of {item.target_max} marks
          {item.grade_label ? ` (${item.grade_label.toLowerCase()})` : ""}.
        </p>
        {((item.input_features.attendance_percentage ?? null) !== null ||
          (item.input_features.internal_marks ?? null) !== null) && (
          <p className="mt-1.5 text-xs text-muted-foreground">
            Signals considered:{" "}
            {(item.input_features.internal_marks ?? null) !== null &&
              `internal marks ${item.input_features.internal_marks!.toFixed(1)}`}
            {(item.input_features.internal_marks ?? null) !== null &&
            (item.input_features.mid_sem_marks ?? null) !== null
              ? ", "
              : ""}
            {(item.input_features.mid_sem_marks ?? null) !== null &&
              `mid-sem marks ${item.input_features.mid_sem_marks!.toFixed(1)}`}
            {(item.input_features.attendance_percentage ?? null) !== null &&
            ((item.input_features.internal_marks ?? null) !== null ||
              (item.input_features.mid_sem_marks ?? null) !== null)
              ? ", "
              : ""}
            {(item.input_features.attendance_percentage ?? null) !== null &&
              `attendance ${item.input_features.attendance_percentage!.toFixed(1)}%`}
            . These are observed signals, not a guarantee.
          </p>
        )}
      </div>
    </div>
  )
}

export function M1V3Card({ data }: { data: M1V3PredictionData }) {
  return (
    <ModelCard
      id="ml-insights-m1v3"
      icon={BookOpen}
      title="Subject end-semester predictions"
      subtitle="Predicted marks on the 0–70 scale with the projected grade band for each of your current subjects."
      badge={<Badge variant="secondary">M1 V3 · Subjects</Badge>}
    >
      {data.subjects.length === 0 ? (
        <div
          role="status"
          className="flex items-start gap-3 rounded-lg border border-dashed px-4 py-5"
        >
          <CircleAlert className="mt-0.5 size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
          <div className="flex flex-col gap-0.5">
            <p className="text-sm font-medium">Not available yet</p>
            <p className="text-xs text-muted-foreground">
              We need more academic records before this prediction can be generated.
            </p>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-3">
          {data.subjects.map((item) => (
            <SubjectRow key={item.subject_id} item={item} />
          ))}
          <p className="text-xs text-muted-foreground">
            {data.note ??
              "Predicted end-sem marks are model estimates, not actual results. This prediction was generated by a model trained on synthetic data. Uncertainty is unavailable for this model."}{" "}
            Model version {data.model_version}.
          </p>
        </div>
      )}
    </ModelCard>
  )
}
