"""M1 V3 — prediction response schemas (clean model contract).

The M1 V3 endpoint is a read-only GET (no request body). Response models
are for the CLEAN M1 V3 model ("m1_v3_clean", HistGradientBoostingRegressor,
38-feature "C_core_history_learning" contract — see
ml/M1_v3_CampusX_package/schema/features.json).

Subject-level input features surfaced per prediction:
  internal_marks, mid_sem_marks, pre_endsem_assessment_pct,
  assignment_score, quiz_avg_marks, submission_delay_days, credits.
attendance_percentage is retained as a nullable field purely for contract
stability and is always null for this model (attendance is not an input of
the clean model).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class M1V3SubjectInputFeatures(BaseModel):
    """Input features surfaced per predicted subject (from the 38-feature contract).

    Fields from the C_core_history_learning subject-level group:
      - internal_marks: 0–20, pre-end-sem internal component
      - mid_sem_marks: 0–50, mid-exam marks
      - pre_endsem_assessment_pct: 0–100, pre-end-sem assessment aggregate
      - assignment_score: 0–100, continuous assessment score
      - quiz_avg_marks: 0–100, average quiz marks
      - submission_delay_days: ≥0, total submission delay days
      - credits: subject credit value
      - attendance_percentage: always null (not an input of the clean model;
        retained for contract stability only)
    """

    internal_marks: float | None = None
    mid_sem_marks: float | None = None
    pre_endsem_assessment_pct: float | None = Field(default=None, ge=0.0, le=100.0)
    assignment_score: float | None = Field(default=None, ge=0.0, le=100.0)
    quiz_avg_marks: float | None = Field(default=None, ge=0.0, le=100.0)
    submission_delay_days: float | None = Field(default=None, ge=0.0)
    attendance_percentage: float | None = Field(default=None, ge=0.0, le=100.0)
    credits: int | None = None

    model_config = ConfigDict(extra="forbid")


class M1V3SubjectPrediction(BaseModel):
    """One predicted subject end-sem mark (model output, not an actual result)."""

    subject_id: str
    subject_name: str | None = None
    semester_no: int
    predicted_end_sem_marks: float = Field(ge=0.0, le=70.0)
    target_max: float = 70.0
    grade_band: str
    grade_label: str
    input_features: M1V3SubjectInputFeatures = Field(
        default_factory=M1V3SubjectInputFeatures
    )

    model_config = ConfigDict(extra="forbid")


class M1V3PredictionResponse(BaseModel):
    """Full M1 V3 prediction result for a student (read-only inference)."""

    student_id: str
    model_id: str = "m1_v3"
    model_version: str
    algorithm: str | None = None
    readiness_status: Literal["READY", "NO_DATA"]
    reason: str | None = None
    current_semester: int | None = None
    prediction_count: int
    predicted_at: datetime
    inference_ms: float | None = None
    subjects: list[M1V3SubjectPrediction] = Field(default_factory=list)
    note: str | None = Field(
        default="Predicted end-sem marks are model estimates, not actual results. "
        "This prediction was generated by the M1 V3 clean model "
        "(HistGradientBoostingRegressor, 38-feature contract) trained on real "
        "CampusX data. Uncertainty is unavailable for this model.",
    )

    model_config = ConfigDict(extra="forbid")


class M1V3Error(BaseModel):
    """Structured error detail for the M1 V3 endpoint."""

    detail: str
    code: str | None = None

    model_config = ConfigDict(extra="forbid")
