"""M1 V3 — prediction response schemas (synthetic-trained model contract).

The M1 V3 endpoint is a read-only GET (no request body). Response models
mirror M1 V2 but with the 8-feature input contract:

  1. internal_marks
  2. mid_sem_marks
  3. attendance_percentage
  4. credits
  5. semester_no
  6. subject_type
  7. department_name
  8. gender
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class M1V3SubjectInputFeatures(BaseModel):
    """Input features surfaced per predicted subject."""

    internal_marks: float | None = None
    mid_sem_marks: float | None = None
    attendance_percentage: float | None = Field(default=None, ge=0.0, le=100.0)
    credits: int | None = None

    model_config = ConfigDict(extra="forbid")


class M1V3SubjectPrediction(BaseModel):
    """One predicted subject end-sem mark (model output, not an actual result)."""

    subject_id: str
    subject_name: str | None = None
    semester_no: int
    predicted_end_sem_marks: float = Field(ge=0.0, le=70.0)
    target_max: float = 70.0
    grade_band: str
    grade_label: str
    input_features: M1V3SubjectInputFeatures = Field(
        default_factory=M1V3SubjectInputFeatures
    )

    model_config = ConfigDict(extra="forbid")


class M1V3PredictionResponse(BaseModel):
    """Full M1 V3 prediction result for a student (read-only inference)."""

    student_id: str
    model_id: str = "m1_v3"
    model_version: str
    algorithm: str | None = None
    readiness_status: Literal["READY", "NO_DATA"]
    reason: str | None = None
    current_semester: int | None = None
    prediction_count: int
    predicted_at: datetime
    inference_ms: float | None = None
    subjects: list[M1V3SubjectPrediction] = Field(default_factory=list)
    note: str | None = Field(
        default="Predicted end-sem marks are model estimates, not actual results. "
        "This prediction was generated by a model trained on synthetic data. "
        "Uncertainty is unavailable for this model.",
    )

    model_config = ConfigDict(extra="forbid")


class M1V3Error(BaseModel):
    """Structured error detail for the M1 V3 endpoint."""

    detail: str
    code: str | None = None

    model_config = ConfigDict(extra="forbid")
